# Generated by Django 3.1.5 on 2021-02-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_h', models.CharField(max_length=44)),
                ('date_of_posts', models.DateField(blank=True)),
                ('text_of_posr', models.CharField(max_length=2000)),
                ('post_image', models.ImageField(upload_to='post_image/')),
            ],
        ),
    ]
